/*
 * File: app/view/AdminViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.AdminViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.admin',

    singin: function(button, e, eOpts) {
        const access_token = localStorage.getItem('access_token');;

        Ext.Ajax.request({
            url:'http://auth.test/api/auth/logout',
            method:"POST",
            headers:{
                'Authorization':`Bearer ${access_token}`
            },
            success:(response)=>{
                const result = Ext.decode(response.responseText);
                this.getView().destroy();
                localStorage.removeItem('access_token');
                localStorage.removeItem('ttl');

                Ext.create('app.view.App').show();

            },
            failure:(response)=>{
                const result = Ext.decode(response.responseText);
                console.log(result);
            }
        });



    },

    onViewportAfterRender: function(component, eOpts) {
        const access_token = localStorage.getItem('access_token');
        const title = Ext.getCmp('title-admin-user');
        const role = Ext.getCmp('title-admin-rol');
        const table = Ext.getCmp('table-user');

        //myaccount
        Ext.Ajax.request({
            url:'http://auth.test/api/auth/myaccount',
            method:'POST',
            headers:{
                'Authorization':`Bearer ${access_token}`
            },
            success:(response)=>{
                const result = Ext.decode(response.responseText);
                console.log(result);
                title.el.dom.innerHTML = `Bienvenido ${result.data.name} ${result.data.lastname}`;
                role.el.dom.innerHTML = `Tu rol es ${result.data.role}`;
            },
            failure:(response)=>{
                const result = Ext.decode(response.responseText);
                console.log(result);
            }
        });

        //table info
        Ext.Ajax.request({
            url:'http://auth.test/api/user/find/all',
            headers:{
                'Authorization':`Bearer ${access_token}`
            },
            success:(response)=>{
                const result = Ext.decode(response.responseText);
                console.log(result);

                table.setStore(result.data);
            },
            failure:(response)=>{
                const result = Ext.decode(response.responseText);
                console.log(result);
            }
        });



    }

});
