/*
 * File: app/view/App.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.App', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.app',

    requires: [
        'app.view.AppViewModel',
        'app.view.AppViewController'
    ],

    controller: 'app',
    viewModel: {
        type: 'app'
    },
    cls: 'login-background',
    height: 250,
    style: 'background:#27272a;',
    width: 400,

    listeners: {
        afterrender: 'onViewportAfterRender',
        beforerender: 'onViewportBeforeRender'
    }

});