/*
 * File: app/view/AppViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.AppViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.app',

    onViewportAfterRender: function(component, eOpts) {
        const access_token = localStorage.getItem('access_token');


        if(!access_token){
            Ext.create('app.view.Login').show();
        }else{

            Ext.Ajax.request({
                url:'http://auth.test/api/auth/myaccount',
                method:'POST',
                headers:{
                    'Authorization':`Bearer ${access_token}`,
                },
                success:(response)=>{
                    // console.log(response.getAllResponseHeaders());
                    console.log(response);
                    const result = Ext.decode(response.responseText);
                    console.log(result);




                    const role = result.data.role;
                    //Ext.create('app.view.Admin').show();


                    if(role.find((e)=>e==='user')==='user'){
                        Ext.create('app.view.User').show();
                    }

                    if(role.find((e)=>e==='admin')==='admin'){
                        Ext.create('app.view.Admin').show();
                    }


                },
                failure:(response)=>{
                    const result = Ext.decode(response.responseText);
                    console.log(result);
                }
            });

        }
    },

    onViewportBeforeRender: function(component, eOpts) {
        Ext.Ajax.on('requestcomplete', function ( conn, response, options ) {
            const { token, ttl } = response.getAllResponseHeaders();

            if(token && ttl){
                localStorage.setItem('ttl', ttl);
                localStorage.setItem('access_token', token);
            }
        });
    }

});
