/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.Login', {
    extend: 'Ext.window.Window',
    alias: 'widget.login',

    requires: [
        'app.view.LoginViewModel',
        'app.view.LoginViewController',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'login',
    viewModel: {
        type: 'login'
    },
    shadow: false,
    autoShow: true,
    border: false,
    cls: 'border-none',
    height: 250,
    resizable: false,
    userCls: 'border-none',
    width: 400,
    referenceHolder: true,
    bodyCls: 'border-none',
    header: false,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            shadow: false,
            border: false,
            cls: 'border-none',
            height: '100%',
            style: 'background:#404040;',
            userCls: 'border-none',
            bodyCls: 'border-none',
            bodyPadding: 10,
            bodyStyle: 'background:#404040;',
            frameHeader: false,
            header: false,
            title: 'Inicio de Sesión',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'label',
                    cls: 'title',
                    style: 'color:white; text-align:center; margin-bottom:20px; font-size:24px; margin-top:20px;',
                    width: '100%',
                    text: 'Inicio de Sesión'
                },
                {
                    xtype: 'label',
                    style: 'color:white;',
                    text: 'Correo'
                },
                {
                    xtype: 'textfield',
                    style: 'background:#52525b;',
                    fieldLabel: 'Correo',
                    hideLabel: true,
                    name: 'email',
                    validation: true,
                    inputType: 'email',
                    vtype: 'email'
                },
                {
                    xtype: 'label',
                    style: 'color:white;',
                    text: 'Contraseña'
                },
                {
                    xtype: 'textfield',
                    style: 'background:#52525b !important;',
                    width: '100%',
                    fieldLabel: 'Contraseña',
                    hideEmptyLabel: false,
                    hideLabel: true,
                    name: 'password',
                    validation: true,
                    inputType: 'password'
                },
                {
                    xtype: 'container',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            anchor: '',
                            cls: 'btn-green',
                            style: 'text-transform:uppercase; letter-spacing:1; border-witdh:0;',
                            width: 200,
                            text: 'aceptar',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender'
    }

});