/*
 * File: app/view/Task.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.Task', {
    extend: 'Ext.window.Window',
    alias: 'widget.task',

    requires: [
        'app.view.TaskViewModel',
        'app.view.TaskViewController',
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    controller: 'task',
    viewModel: {
        type: 'task'
    },
    modal: true,
    border: false,
    draggable: false,
    minWidth: 300,
    resizable: false,
    overlapHeader: false,
    title: 'Agregar nueva tarea',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            frameHeader: false,
            header: false,
            title: 'My Form',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textareafield',
                    flex: 1,
                    fieldLabel: 'Label',
                    hideLabel: true,
                    name: 'content'
                },
                {
                    xtype: 'container',
                    height: 86,
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            width: 150,
                            text: 'ACEPTAR',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            style: 'margin-top:10px;',
                            text: 'CANCELAR',
                            listeners: {
                                click: 'onButtonClickCancel'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});