/*
 * File: app/view/TaskViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.TaskViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.task',

    onButtonClick: function(button, e, eOpts) {
        const access_token = localStorage.getItem('access_token');
        const table = Ext.getCmp('table-complete');
        const form = button.up('form').getForm();
        const { content } = form.getValues();

        Ext.Ajax.request({
            url:'http://auth.test/api/task/add',
            method:'POST',
            headers:{
                'Authorization':`Bearer ${access_token}`
            },
            params:{
                content
            },
            success:({responseText})=>{
            const result = Ext.decode(responseText);
            if(result.success){
                table.store.add(result.data);
                this.getView().destroy();
            }
        },
        failure:({responseText})=>{
        const result = Ext.decode(responseText);
        console.log(result);
    }
});
    },

    onButtonClickCancel: function(button, e, eOpts) {

        this.getView().destroy();





    }

});
